### ISSUE TITLE
Issues while upgrading from absinthe_relay from 1.4 to 1.5

### ISSUE THREAD

**Issue by anildigital** [absinthe-graphql/absinthe_relay#206]
I am getting following error when I upgraded from absinthe_relay version from 1.4.x to 1.5.x

```bash
mix compile
==> absinthe_relay
Compiling 19 files (.ex)
Generated absinthe_relay app
==> myapp
Compiling 46 files (.ex)

== Compilation error in file lib/myapp_web/graphql/schema.ex ==
** (FunctionClauseError) no function clause matching in Keyword.pop/3

    The following arguments were given to Keyword.pop/3:

        # 1
        MyAppWeb.GraphQL

        # 2
        :id_type

        # 3
        :id

    Attempted function clauses (showing 1 out of 1):

        def pop(keywords, key, default) when is_list(keywords) and is_atom(key)

    (elixir 1.12.3) lib/keyword.ex:1043: Keyword.pop/3
    (absinthe_relay 1.5.2) lib/absinthe/relay/node/notation.ex:49: Absinthe.Relay.Node.Notation.do_interface/3
    (absinthe_relay 1.5.2) expanding macro: Absinthe.Relay.Node.Notation.node/2
    lib/myapp_web/graphql/schema.ex:2: MyAppWeb.GraphQL.Schema (module)
    expanding macro: MyAppWeb.GraphQL.__using__/1
    lib/myapp_web/graphql/schema.ex:2: MyAppWeb.GraphQL.Schema (module)
    (elixir 1.12.3) expanding macro: Kernel.use/2
```

Anyone know what could be the reason? Thank you

**Comment by benwilson512** [comment]
Hi @anildigital without example code that demonstrates the issue I don't know how to help.
